### ISSUE TITLE
Statistics Buff

### ISSUE THREAD

**Issue by KO4JZT** [knights-of-academia/pom-bot#1]
- [x] Show how many minutes/hours they have pommed in their current session (in !poms output)

**Comment by clayboone** [comment]
I this is done.

**Comment by deadbender** [comment]
@clayboone 👍🏻 I'll leave this up just in case I think of any other interesting additions.

**Comment by clayboone** [comment]
#72 adds more here as well.

It's been almost a year with no interesting results. I'm closing this.
