### ISSUE TITLE
Pom isn't registering with a space after the !

### ISSUE THREAD

**Issue by Cka404** [knights-of-academia/pom-bot#10]
I've noticed that when some people are using auto suggestion/ correct or swipe on their phones it creates a space between the ! and the word (pom, raid etc) and then it doesn't register said pom (or raid). 

- Steps to reproduce:
 1. Open the Pom Bank channel
 2. Enter `! pom` 
 
- Expected Behaviour:
 
   A Pom is registered.

- Actual Behaviour:

   A Pom is not registered.

**Comment by clayboone** [comment]
This is resolved. One space is supported, after that, the message is not treated as a command.
