### ISSUE TITLE
POM_CHANNEL_ID not working

### ISSUE THREAD

**Issue by resignedangel** [knights-of-academia/pom-bot#4]
`POM_CHANNEL_ID = int(os.getenv(''))` is not working and returns `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

I guess it should be `POM_CHANNEL_ID = os.getenv('')` 

Didn't know if I should create a PR.

**Comment by deadbender** [comment]
It should be an integer, you don't have anything set for an environment variable there so it's grabbing null.

To fix this on your local dev environment you can do `POM_CHANNEL_ID = 0000000` with the 0s replaced by a Discord channel's ID. Just be sure to remove it before submitting a PR.

**Comment by deadbender** [comment]
We should definitely make that a better configuration, so I'll leave this issue open.

**Comment by clayboone** [comment]
This is fixed. We use a channel name now in the `/.env` file.
