### ISSUE TITLE
Custom emotes for pom and defend

### ISSUE THREAD

**Issue by zmontgo** [knights-of-academia/pom-bot#61]
`:pom:` is for the emote a user sees upon logging an action. Currently, it is 🍅, and it should be `:pom:`. For defends, the bot reacts with 🛡️, and it should be `:defend:`.

**Comment by clayboone** [comment]
I'm closing this issue because, during Pom Wars Season 3, custom emotes for `!attack` and `!defend` were implemented.

In the future, another, more-specific ticket can be raised.
